name: Daemon Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: update apt repos
        run: sudo apt update

      - name: install dependencies
        run: sudo apt install -y libudev-dev librust-pango-sys-dev

      - name: Run cargo tests
        uses: actions-rs/cargo@v1
        with:
          command: test
